### PR TITLE
WIP: Post SAT commit

### PR DESCRIPTION
**Pull request by sfsyunusSLAC**
- Updated NC and CoE configs

- Added axis parameters xml

- Run pre-commit hooks

### CODE REVIEW

**Comment by sfsyunusSLAC** [comment]
@ZLLentz things are looking a bit better now after tracking all the IO individually, and running the pre-commit hooks (great tool!) but the docs build still fails
`TypeError: '<' not supported between instances of 'str' and 'NoneType'`
Is this more formatting issues?

**Comment by ZLLentz** [comment]
That looks like an internal error with sorting a list of strings, e.g. there was a random `None` inside the list and the sorting algorithm died.

@klauer, any ideas about why jinja would fail in ads_ioc like this? I'm having trouble making sense of it.

**Comment by ZLLentz** [comment]
Well, specifically this is failing on the tsproj links summary, so it's possible that there's a broken link in the project that's mucking everything up...

**Comment by klauer** [comment]
Hmm, sorry you're running into this. Not sure why the links would be problematic, but I will take a look in the morning (ping me if I forget)

**Comment by klauer** [comment]
Pushed a hotfix to ads-deploy. Should be good-to-go 👍

**Pull request merged**
