### PR TITLE
WIP: Updated motion lib to v1.3.1, set up TC best practices

### PR DESCRIPTION
**Pull request by sfsyunusSLAC**
- Updated to newer lcls-twincat-motion library v1.3.1

- Updated MAIN -> Main for future IOC deployment

- Added pragmas for STOs

- Added I/O to version control

- Removed individual line IDs

### CODE REVIEW

**Comment by sfsyunusSLAC** [comment]
@ZLLentz no rush but at some point could you help me parse the travis checks that are failing for this

**Comment by ZLLentz** [comment]
RE: Travis:

- `pre-commit` has a lot of strict style rules that should be self-explanatory, except it also wants a cleanly reformatted .tmc file to make it readable. We can make these not required to pass if you need to press on and address functional changes rather than deal with style.
- The linter and docs builder are both freaking out for the same reason, I need to dig a bit to see why

**Comment by ZLLentz** [comment]
Best I can tell, the project is currently inconsistent between which items are saved in separate files and which are saved in the same file. You may need to go to every element in your IO tree and verify that they are set up to be saved in a separate file.

Changing the TwinCAT configuration from same files to split files does not go through your project and adjust it accordingly... Which is annoying.

**Comment by ZLLentz** [comment]
https://github.com/pcdshub/M2K2/blob/9da4375cb9c259a193c4439311b64e663d9ff92d/.travis.yml#L14-L18 is where you would make a change if you want to disable style checks and pre-commit checks from giving you the red x here.

**Pull request merged**
